# Generated by Django 5.2.1 on 2025-06-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(null=True, verbose_name=models.CharField(max_length=40, null=True, unique=True)),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
