# Generated by Django 5.2.1 on 2025-06-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_slug_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
    ]
