# Generated by Django 5.2.1 on 2025-06-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='user_role',
            field=models.CharField(choices=[('VIEWER', 'читатель'), ('EDITOR', 'редактор'), ('OWNER', 'администратор')], max_length=10),
        ),
    ]
