# Generated by Django 5.2.1 on 2025-06-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectmember_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PUBLIC', 'публичный'), ('PRIVATE', 'приватный')], default='PUBLIC', max_length=20, null=True),
        ),
    ]
