# Generated by Django 5.2.1 on 2025-06-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_completed',
            field=models.CharField(choices=[('NO', 'В работе'), ('YES', 'Выполнено')], default='NO', max_length=20, null=True),
        ),
    ]
