# Generated by Django 5.2.1 on 2025-06-08 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectmember',
            old_name='user_id',
            new_name='user',
        ),
    ]
