# Generated by Django 5.2.1 on 2025-06-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_project_id_projectmember_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='user_role',
            field=models.CharField(choices=[('VIEWER', 'Читатель'), ('EDITOR', 'Редактор'), ('OWNER', 'Администратор')], max_length=10),
        ),
    ]
