# Generated by Django 5.2.1 on 2025-06-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'низкий'), ('MEDIUM', 'средний'), ('HIGH', 'высокий')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'новая'), ('INPR', 'в работе'), ('DONE', 'сделано')], default='NEW', max_length=10),
        ),
    ]
