# Generated by Django 5.2.1 on 2025-06-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('INPR', 'В работе'), ('DONE', 'Сделано')], default='NEW', max_length=10),
        ),
    ]
