# Generated by Django 5.2.1 on 2025-06-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_project_id_task_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='task_id',
            new_name='task',
        ),
    ]
